<script>
  let { country = '' } = $props();

  const playlists = {
    'Afghanistan': 'https://open.spotify.com/embed/playlist/562K7759REapjUDAJmEszO',
    'Albania': 'https://open.spotify.com/embed/playlist/0fQQvZeZjLH3x2VJIBDJkC',
    'Algeria': 'https://open.spotify.com/embed/playlist/4SqOaWmWrUMhCJS46Aw7Zi',
    'Andorra': 'https://open.spotify.com/embed/playlist/4h0jGZdu6jRk57JFmWX98e',
    'Angola': 'https://open.spotify.com/embed/playlist/2diUVDFxNHNzERh89Ud1PO',
    'Antigua and Barbuda': 'https://open.spotify.com/embed/playlist/0IBqePgljttwsnQtC4VnHt',
    'Argentina': 'https://open.spotify.com/embed/playlist/70yDbCeImYqhxCDRU0qXpd',
    'Australia': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX8AT3JQY6jMQ',
    'Austria': 'https://open.spotify.com/embed/playlist/2pEF8qW6YyLXvEOflWiPTz',
    'Azerbaijan': 'https://open.spotify.com/embed/playlist/6raSpwYnvMoNwAPM19qJNO',
    'Bahamas': 'https://open.spotify.com/embed/playlist/0rSWozhTVMRbDa6Afqn90f',
    'Bahrain': 'https://open.spotify.com/embed/playlist/3EzjmrR684StT60sFCtiXV',
    'Bangladesh': 'https://open.spotify.com/embed/playlist/7yrj1xq9wOYCwUjwBAOQH1',
    'Barbados': 'https://open.spotify.com/embed/playlist/3l8Nhp4GPTGS1yShqeYO4R',
    'Belarus': 'https://open.spotify.com/embed/playlist/5TFINGM4z20SZ0NIi2ILPh',
    'Belgium': 'https://open.spotify.com/embed/playlist/15lUfs9HAkNrylxs8MjotV',
    'Belize': 'https://open.spotify.com/embed/playlist/5De0LxHjPVc5f7VDmU0mR9',
    'Benin': 'https://open.spotify.com/embed/playlist/79dI3gsjQLBROYfyd7F9D6',
    'Bhutan': 'https://open.spotify.com/embed/playlist/430q5CT3xAc9sbZRQnNc3f',
    'Bolivia': 'https://open.spotify.com/embed/playlist/3SwCXSJe5qaCRlxud8SDuU',
    'Bosnia Herzegovina': 'https://open.spotify.com/embed/playlist/05KyNXsfxVp8AD7YG9jX2c',
    'Botswana': 'https://open.spotify.com/embed/playlist/05evU2O58XihdI43chE5Iy',
    'Brazil': 'https://open.spotify.com/embed/playlist/45qU9DK3tOzC64EkUpMzMO',
    'Brunei': 'https://open.spotify.com/embed/playlist/4buZWh6IvedusMWSLGaHfP',
    'Bulgaria': 'https://open.spotify.com/embed/playlist/2xmIu0wJpdfWRnEJL6fi1j',
    'Burkina Faso': 'https://open.spotify.com/embed/playlist/5qhQvsGMW5sM40R7J9J81k',
    'Burundi': 'https://open.spotify.com/embed/playlist/1mRpE6qCP9aKMqrkzoUTto',
    'Cambodia': 'https://open.spotify.com/embed/playlist/3wFjS6ofvnNWK5qL86OwX9',
    'Cameroon': 'https://open.spotify.com/embed/playlist/39t3BhdVssvlUjBHDOjQVi',
    'Canada': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX4bKgmgKIPtO',
    'Cape Verde': 'https://open.spotify.com/embed/playlist/0BYefINm7OMPZWCgcoXjUp',
    'Central African Republic': 'https://open.spotify.com/embed/playlist/0Wd7ru6M2A4bqzvCTUtQ3Z',
    'Chad': 'https://open.spotify.com/embed/playlist/4id4jU46jt19nZAiUoM24X',
    'Chile': 'https://open.spotify.com/embed/playlist/7KMdeUQonqkwfR4PTzB8Ul',
    'China': 'https://open.spotify.com/embed/playlist/0cRMik0zbSVLh1aRiKfnyz',
    'Colombia': 'https://open.spotify.com/embed/playlist/7eMCizJClROuIHezAeF1QQ',
    'Comoros': 'https://open.spotify.com/embed/playlist/6CQ7BByKubkBWGiWqHlUbS',
    'Congo {Democratic Rep}': 'https://open.spotify.com/embed/playlist/0OoMGryL6RnbWuAThKsC34',
    'Costa Rica': 'https://open.spotify.com/embed/playlist/3jUe2PWeVUQGyqlnNbd2pf',
    'Croatia': 'https://open.spotify.com/embed/playlist/04gcP0h0bvpqkjN4GSOAjG',
    'Cuba': 'https://open.spotify.com/embed/playlist/2040n5A1wal0GRcz9MNBYS',
    'Cyprus': 'https://open.spotify.com/embed/playlist/0wGTFQnxA48UDzNKI0LNwa',
    'Czech Republic': 'https://open.spotify.com/embed/playlist/15bj6pk49miONOa3aCM20q',
    'Denmark': 'https://open.spotify.com/embed/playlist/7nFCqf4OyjdWNkYVCr2LDH',
    'Djibouti': 'https://open.spotify.com/embed/playlist/03thGBPAS6E4h4IV9wijzm',
    'Dominica': 'https://open.spotify.com/embed/playlist/7EIOYgdso5QpPBRMUCSF9N',
    'Dominican Republic': 'https://open.spotify.com/embed/playlist/0Kh97QBYQ8OtUI8Mk8U09a',
    'East Timor': 'https://open.spotify.com/embed/playlist/7nxGrqThvp577vV0oVgf3F',
    'Ecuador': 'https://open.spotify.com/embed/playlist/6nYabBtp0o1uD7Tzr95P0m',
    'Egypt': 'https://open.spotify.com/embed/playlist/4rEtMrHwDiLltcbnyMh33T',
    'El Salvador': '',
    'Equatorial Guinea': '',
    'Eritrea': '',
    'Estonia': '',
    'Ethiopia': '',
    'Fiji': '',
    'Finland': '',
    'France': '',
    'Gabon': '',
    'Gambia': '',
    'Georgia': '',
    'Germany': '',
    'Ghana': '',
    'Greece': '',
    'Grenada': '',
    'Guatemala': '',
    'Guinea': '',
    'Guinea-Bissau': '',
    'Guyana': '',
    'Haiti': '',
    'Honduras': '',
    'Hungary': '',
    'Iceland': '',
    'India': '',
    'Indonesia': '',
    'Iran': '',
    'Iraq': '',
    'Ireland {Republic}': '',
    'Israel': '',
    'Italy': '',
    'Ivory Coast': '',
    'Jamaica': '',
    'Japan': '',
    'Jordan': '',
    'Kazakhstan': '',
    'Kenya': '',
    'Kiribati': '',
    'Korea North': '',
    'Korea South': '',
    'Kosovo': '',
    'Kuwait': '',
    'Kyrgyzstan': '',
    'Laos': '',
    'Latvia': '',
    'Lebanon': '',
    'Lesotho': '',
    'Liberia': '',
    'Libya': '',
    'Liechtenstein': '',
    'Lithuania': '',
    'Luxembourg': '',
    'Macedonia': '',
    'Madagascar': '',
    'Malawi': '',
    'Malaysia': '',
    'Maldives': '',
    'Mali': '',
    'Malta': '',
    'Marshall Islands': '',
    'Mauritania': '',
    'Mauritius': '',
    'Mexico': '',
    'Micronesia': '',
    'Moldova': '',
    'Monaco': '',
    'Mongolia': '',
    'Montenegro': '',
    'Morocco': '',
    'Mozambique': '',
    'Myanmar, {Burma}': '',
    'Namibia': '',
    'Nauru': '',
    'Nepal': '',
    'Netherlands': '',
    'New Zealand': '',
    'Nicaragua': '',
    'Niger': '',
    'Nigeria': '',
    'Norway': '',
    'Oman': '',
    'Pakistan': '',
    'Palau': '',
    'Panama': '',
    'Papua New Guinea': '',
    'Paraguay': '',
    'Peru': '',
    'Philippines': '',
    'Poland': '',
    'Portugal': '',
    'Qatar': '',
    'Romania': '',
    'Russian Federation': '',
    'Rwanda': '',
    'St Kitts & Nevis': '',
    'St Lucia': '',
    'Saint Vincent & the Grenadines': '',
    'Samoa': '',
    'San Marino': '',
    'Sao Tome & Principe': '',
    'Saudi Arabia': '',
    'Senegal': '',
    'Serbia': '',
    'Seychelles': '',
    'Sierra Leone': '',
    'Singapore': '',
    'Slovakia': '',
    'Slovenia': '',
    'Solomon Islands': '',
    'Somalia': '',
    'South Africa': '',
    'South Sudan': '',
    'Spain': '',
    'Sri Lanka': '',
    'Sudan': '',
    'Suriname': '',
    'Swaziland': '',
    'Sweden': '',
    'Switzerland': '',
    'Syria': '',
    'Taiwan': '',
    'Tajikistan': '',
    'Tanzania': '',
    'Thailand': '',
    'Togo': '',
    'Tonga': '',
    'Trinidad & Tobago': '',
    'Tunisia': '',
    'Turkey': '',
    'Turkmenistan': '',
    'Tuvalu': '',
    'Uganda': '',
    'Ukraine': '',
    'United Arab Emirates': '',
    'United Kingdom': '',
    'United States': '',
    'Uruguay': '',
    'Uzbekistan': '',
    'Vanuatu': '',
    'Vatican City': '',
    'Venezuela': '',
    'Vietnam': '',
    'Yemen': '',
    'Zambia': '',
    'Zimbabwe':
  };

  const getPlaylist = (countryName) => playlists[countryName] || '';
</script>

<div class="bg-white rounded-lg shadow-lg p-4 max-w-sm mx-auto mt-4">
  <h3 class="text-xl font-bold mb-2">Country Info</h3>
  <p class="text-lg">{country || '(no data)'}</p>
  <hr class="my-3" />
  {#if getPlaylist(country)}
  <iframe
    data-testid="embed-iframe"
    title="Spotify playlist"
    style="border-radius:12px"
    src={getPlaylist(country)}
    width="100%"
    height="352"
    frameborder="0"
    allowfullscreen
    allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
    loading="lazy"
  ></iframe>

  {:else if country && country !== 'Loading...' && country !== 'Country not found' && country !== 'Error fetching country'}
  <p class="text-sm mt-3 text-gray-600">No playlist mapped for {country} yet.</p>
  {/if}
</div>

