<script>
  let { country = '' } = $props();

  const playlists = {
    'Afghanistan': 'https://open.spotify.com/embed/playlist/562K7759REapjUDAJmEszO',
    'Albania': 'https://open.spotify.com/embed/playlist/0fQQvZeZjLH3x2VJIBDJkC',
    'Algeria': 'https://open.spotify.com/embed/playlist/4SqOaWmWrUMhCJS46Aw7Zi',
    'Andorra': 'https://open.spotify.com/embed/playlist/4h0jGZdu6jRk57JFmWX98e',
    'Angola': 'https://open.spotify.com/embed/playlist/2diUVDFxNHNzERh89Ud1PO',
    'Antigua and Barbuda': 'https://open.spotify.com/embed/playlist/0IBqePgljttwsnQtC4VnHt',
    'Argentina': 'https://open.spotify.com/embed/playlist/70yDbCeImYqhxCDRU0qXpd',
    'Australia': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX8AT3JQY6jMQ',
    'Austria': 'https://open.spotify.com/embed/playlist/2pEF8qW6YyLXvEOflWiPTz',
    'Azerbaijan': 'https://open.spotify.com/embed/playlist/6raSpwYnvMoNwAPM19qJNO',
    'Bahamas': 'https://open.spotify.com/embed/playlist/0rSWozhTVMRbDa6Afqn90f',
    'Bahrain': 'https://open.spotify.com/embed/playlist/3EzjmrR684StT60sFCtiXV',
    'Bangladesh': 'https://open.spotify.com/embed/playlist/7yrj1xq9wOYCwUjwBAOQH1',
    'Barbados': 'https://open.spotify.com/embed/playlist/3l8Nhp4GPTGS1yShqeYO4R',
    'Belarus': 'https://open.spotify.com/embed/playlist/5TFINGM4z20SZ0NIi2ILPh',
    'Belgium': 'https://open.spotify.com/embed/playlist/15lUfs9HAkNrylxs8MjotV',
    'Belize': 'https://open.spotify.com/embed/playlist/5De0LxHjPVc5f7VDmU0mR9',
    'Benin': 'https://open.spotify.com/embed/playlist/79dI3gsjQLBROYfyd7F9D6',
    'Bhutan': 'https://open.spotify.com/embed/playlist/430q5CT3xAc9sbZRQnNc3f',
    'Bolivia': 'https://open.spotify.com/embed/playlist/3SwCXSJe5qaCRlxud8SDuU',
    'Bosnia Herzegovina': 'https://open.spotify.com/embed/playlist/05KyNXsfxVp8AD7YG9jX2c',
    'Botswana': 'https://open.spotify.com/embed/playlist/05evU2O58XihdI43chE5Iy',
    'Brazil': 'https://open.spotify.com/embed/playlist/45qU9DK3tOzC64EkUpMzMO',
    'Brunei': 'https://open.spotify.com/embed/playlist/4buZWh6IvedusMWSLGaHfP',
    'Bulgaria': 'https://open.spotify.com/embed/playlist/2xmIu0wJpdfWRnEJL6fi1j',
    'Burkina Faso': 'https://open.spotify.com/embed/playlist/5qhQvsGMW5sM40R7J9J81k',
    'Burundi': 'https://open.spotify.com/embed/playlist/1mRpE6qCP9aKMqrkzoUTto',
    'Cambodia': 'https://open.spotify.com/embed/playlist/3wFjS6ofvnNWK5qL86OwX9',
    'Cameroon': 'https://open.spotify.com/embed/playlist/39t3BhdVssvlUjBHDOjQVi',
    'Canada': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX4bKgmgKIPtO',
    'Cape Verde': 'https://open.spotify.com/embed/playlist/0BYefINm7OMPZWCgcoXjUp',
    'Central African Republic': 'https://open.spotify.com/embed/playlist/0Wd7ru6M2A4bqzvCTUtQ3Z',
    'Chad': 'https://open.spotify.com/embed/playlist/4id4jU46jt19nZAiUoM24X',
    'Chile': 'https://open.spotify.com/embed/playlist/7KMdeUQonqkwfR4PTzB8Ul',
    'China': 'https://open.spotify.com/embed/playlist/0cRMik0zbSVLh1aRiKfnyz',
    'Colombia': 'https://open.spotify.com/embed/playlist/7eMCizJClROuIHezAeF1QQ',
    'Comoros': 'https://open.spotify.com/embed/playlist/6CQ7BByKubkBWGiWqHlUbS',
    'Congo {Democratic Rep}': 'https://open.spotify.com/embed/playlist/0OoMGryL6RnbWuAThKsC34',
    'Costa Rica': 'https://open.spotify.com/embed/playlist/3jUe2PWeVUQGyqlnNbd2pf',
    'Croatia': 'https://open.spotify.com/embed/playlist/04gcP0h0bvpqkjN4GSOAjG',
    'Cuba': 'https://open.spotify.com/embed/playlist/2040n5A1wal0GRcz9MNBYS',
    'Cyprus': 'https://open.spotify.com/embed/playlist/0wGTFQnxA48UDzNKI0LNwa',
    'Czech Republic': 'https://open.spotify.com/embed/playlist/15bj6pk49miONOa3aCM20q',
    'Denmark': 'https://open.spotify.com/embed/playlist/7nFCqf4OyjdWNkYVCr2LDH',
    'Djibouti': 'https://open.spotify.com/embed/playlist/03thGBPAS6E4h4IV9wijzm',
    'Dominica': 'https://open.spotify.com/embed/playlist/7EIOYgdso5QpPBRMUCSF9N',
    'Dominican Republic': 'https://open.spotify.com/embed/playlist/0Kh97QBYQ8OtUI8Mk8U09a',
    'East Timor': 'https://open.spotify.com/embed/playlist/7nxGrqThvp577vV0oVgf3F',
    'Ecuador': 'https://open.spotify.com/embed/playlist/6nYabBtp0o1uD7Tzr95P0m',
    'Egypt': 'https://open.spotify.com/embed/playlist/4rEtMrHwDiLltcbnyMh33T',
    'El Salvador': 'https://open.spotify.com/embed/playlist/4RsxaHVOxGWbXMTgDSGeX6',
    'Equatorial Guinea': 'https://open.spotify.com/embed/playlist/4ARqVlHq74vvAgexRAagPF',
    'Eritrea': 'https://open.spotify.com/embed/playlist/6zvmdD3Hz5q4AVqc6AUshA',
    'Estonia': 'https://open.spotify.com/embed/playlist/1laLmZpCvHrwRXeSECZkal',
    'Ethiopia': 'https://open.spotify.com/embed/playlist/4E9KpZisCJGzYtDyvNaOo6',
    'Fiji': 'https://open.spotify.com/embed/playlist/5JpWA6PwPccz816XKz2TTK',
    'Finland': 'https://open.spotify.com/embed/playlist/37i9dQZF1DXd7UNY4mzwbR',
    'France': 'https://open.spotify.com/embed/playlist/3eZtF5y5PJX4YpexhHC8dG',
    'Gabon': 'https://open.spotify.com/embed/playlist/4BZEjr7tcmpmeRtnRAPEfN',
    'Gambia': 'https://open.spotify.com/embed/playlist/4suColxugynmjGwji0xjfV',
    'Georgia': 'https://open.spotify.com/embed/playlist/1ggnbwPgliav7xvkTQbRy8',
    'Germany': 'https://open.spotify.com/embed/playlist/25ziWpv0zBpQ2N0OdvHYHE',
    'Ghana': 'https://open.spotify.com/embed/playlist/4G8oE9OHXsxxYeCXczyrPd',
    'Greece': 'https://open.spotify.com/embed/playlist/4U8DgBflU5IRi7EiKuU1s4',
    'Grenada': 'https://open.spotify.com/embed/playlist/2OEuDHDJWjSAoiGkpT79Sc',
    'Guatemala': 'https://open.spotify.com/embed/playlist/6jIkFhakt5MkXCdB4GxqKm',
    'Guinea': 'https://open.spotify.com/embed/playlist/1nDSNgH9o8lPKZyRC9tAwR',
    'Guinea-Bissau': 'https://open.spotify.com/embed/playlist/1yzW52UzOmLqrXKABHjKaU',
    'Guyana': 'https://open.spotify.com/embed/playlist/5tCgnfDlFWA8Uqq5tq2Evy',
    'Haiti': 'https://open.spotify.com/embed/playlist/2AOjOnTGMhk6EZs0nmpZKR',
    'Honduras': 'https://open.spotify.com/embed/playlist/0ZQHY35pKT3qQjdBg6ARMY',
    'Hungary': 'https://open.spotify.com/embed/playlist/2aLuKmjBSjMxD3QIo6ArJm',
    'Iceland': 'https://open.spotify.com/embed/playlist/28eBhAwh4s7NJL8H8PJ5v6',
    'India': 'https://open.spotify.com/embed/playlist/7t8h9JIXRzuZzLlrZWPBmA',
    'Indonesia': 'https://open.spotify.com/embed/playlist/5Wh14KMrdMwRzU4lU8Zc9z',
    'Iran (Islamic Republic of)': 'https://open.spotify.com/embed/playlist/37i9dQZF1DWTdXUHh0Sn4s',
    'Iraq': 'https://open.spotify.com/embed/playlist/1yjEvRfnW6WdMjvHe2FbyQ',
    'Ireland': 'https://open.spotify.com/embed/playlist/2IOdCR21ZTtVioBqgOsJQr',
    'Israel': 'https://open.spotify.com/embed/playlist/6rr1hPgc86HrTwm2wiWyCF',
    'Italy': 'https://open.spotify.com/embed/playlist/4VuLgMrMzBynB4hcMCmYWa',
    'Ivory Coast': 'https://open.spotify.com/embed/playlist/0eK168WNdVOD7Jjb4kW1F8',
    'Jamaica': 'https://open.spotify.com/embed/playlist/7pzraV37tP5kOlADbSJFRK',
    'Japan': 'https://open.spotify.com/embed/playlist/7LzlBR93O6C3rAT8rgtXcN',
    'Jordan': 'https://open.spotify.com/embed/playlist/1HtdKIjYZSKWMLwz4QSDFU',
    'Kazakhstan': 'https://open.spotify.com/embed/playlist/7gfSZXqGtqZr6DS5aYigea',
    'Kenya': 'https://open.spotify.com/embed/playlist/0kDDReaApSTI0wI0kPOqhT',
    'Kiribati': 'https://open.spotify.com/embed/playlist/70XthYU726okIR5AySgLvv',
    'Kosovo': 'https://open.spotify.com/embed/playlist/0SjBtFoPrBveqt80PvOizZ',
    'Kuwait': 'https://open.spotify.com/embed/playlist/0x8Z5eDccde2NrMchEM6MA',
    'Kyrgyzstan': 'https://open.spotify.com/embed/playlist/7r1eHVwCqHvKUSGQb15BjX',
    "Lao People's Democratic Republic (the)": 'https://open.spotify.com/embed/playlist/0yVmsZK4AtiNMpby2WqLZY',
    'Latvia': 'https://open.spotify.com/embed/playlist/6UNk3cgOY4fHzxNBXmSui9',
    'Lebanon': 'https://open.spotify.com/embed/playlist/6rHNgj04KCZqwGnLdGIVEu',
    'Lesotho': 'https://open.spotify.com/embed/playlist/3eBUnJSYgMOx63F6zpSY4U',
    'Liberia': 'https://open.spotify.com/embed/playlist/2ebcBYf5k2MOgQFWkoT4Ej',
    'Libya': 'https://open.spotify.com/embed/playlist/6wgKWnGaWHGrk5f54AF0lp',
    'Liechtenstein': 'https://open.spotify.com/embed/playlist/3AxSX3HPwdYS7HWJOlTUnt',
    'Lithuania': 'https://open.spotify.com/embed/playlist/0jh60zPtx0PsQn8EfLWHw3',
    'Luxembourg': 'https://open.spotify.com/embed/playlist/3mifIDWinWewtstCFuOZsv',
    'Macedonia': 'https://open.spotify.com/embed/playlist/6wk61XRax6dMvX3WClLYbH',
    'Madagascar': 'https://open.spotify.com/embed/playlist/6gcZSDPTVYxaopKWArY5qF',
    'Malawi': 'https://open.spotify.com/embed/playlist/12xQBw7LfT6ml7G9W2LYb4',
    'Malaysia': 'https://open.spotify.com/embed/playlist/4Hg9DU6rTLphuwGx23YMZt',
    'Maldives': 'https://open.spotify.com/embed/playlist/68QPw3QfJyIz3XGKzSgrmL',
    'Mali': 'https://open.spotify.com/embed/playlist/5b9g9F21sYYyQvD4NrcvrN',
    'Malta': 'https://open.spotify.com/embed/playlist/5yaOVyYkN7WdPir2tmyobS',
    'Marshall Islands': 'https://open.spotify.com/embed/playlist/3XacfIDKkS7OKZCgsFB8sz',
    'Mauritania': 'https://open.spotify.com/embed/playlist/6tgiE2xPOzneF0huD1G1eu',
    'Mauritius': 'https://open.spotify.com/embed/playlist/05Ertl48cEF1YAXfsdb945',
    'Mexico': 'https://open.spotify.com/embed/playlist/3YmsmxHmT9BkMPGAbCKMpU',
    'Micronesia': 'https://open.spotify.com/embed/playlist/1dfmaPiBxd3kIAeY3ZT5iC',
    'Moldova': 'https://open.spotify.com/embed/playlist/2DEFWE2xYZaYvBzsabq980',
    'Monaco': '',
    'Mongolia': 'https://open.spotify.com/embed/playlist/0H1CbaHquAZMjljCbSRmYb',
    'Montenegro': 'https://open.spotify.com/embed/playlist/5yY4Ijs7l0cLEftBaOL8X4',
    'Morocco': 'https://open.spotify.com/embed/playlist/1hpVVlVuXSAO50dZOEATah',
    'Mozambique': 'https://open.spotify.com/embed/playlist/4KndbWr6onUEOt1DFhxdIF',
    'Myanmar': 'https://open.spotify.com/embed/playlist/2FT7VePCW7ScsRA25KuenF',
    'Namibia': 'https://open.spotify.com/embed/playlist/4Vs5MwTpqMplF0lfaN6wpY',
    "Korea (the Democratic People's Republic of)": 'https://open.spotify.com/embed/playlist/4i6RABM28rHDmrAAvcN2a5',
    'Nauru': '',
    'Nepal': 'https://open.spotify.com/embed/playlist/4Boop6WQfDfY7Z5J3te0Th',
    'Netherlands': 'https://open.spotify.com/embed/playlist/6upWrJ9tOvVM3zN2tmVRSq',
    'New Zealand': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX4Cwn7U4GsKm',
    'Nicaragua': 'https://open.spotify.com/embed/playlist/2JwhJFWVeyvt8SEQXgmzHM',
    'Niger (the)': '',
    'Nigeria': 'https://open.spotify.com/embed/playlist/5eM577eFgLZ0y6JlcG3ioQ',
    'Norway': 'https://open.spotify.com/embed/playlist/5KsHCxFXRTc5HXCfvbdEfe',
    'Oman': 'https://open.spotify.com/embed/playlist/2kjZeV1jlW3JESiaYT8WPB',
    'Pakistan': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX8ubeHYX0X34',
    'Palau': 'https://open.spotify.com/embed/playlist/6Fr6HDXmioEC83aPfE6Vko',
    'Panama': 'https://open.spotify.com/embed/playlist/2EZy8UaYyU9YfpJDChvKQR',
    'Papua New Guinea': 'https://open.spotify.com/embed/playlist/2DxXbNWF7NyPEiCJoSjARO',
    'Paraguay': 'https://open.spotify.com/embed/playlist/3vGWbwhksMNaxeUKPcO4mM',
    'Peru': 'https://open.spotify.com/embed/playlist/37i9dQZF1DXck9N5J3RmTT',
    'Philippines (the)': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX0iFfuXuP4Pm',
    'Poland': 'https://open.spotify.com/embed/playlist/40uOIq5lmbAApQTlleiVp0',
    'Portugal': 'https://open.spotify.com/embed/playlist/1Rn01P3YPioy5QRQoo32Lv',
    'Qatar': 'https://open.spotify.com/embed/album/3RY5pvPoATK2hOVOeVvMkY',
    'Romania': 'https://open.spotify.com/embed/playlist/68oBTMg4kV2C1UXDAxOmeH',
    'Russian Federation (the)': 'https://open.spotify.com/embed/playlist/2Rddr1ukTfxifThECMJFvu',
    'Rwanda': 'https://open.spotify.com/embed/playlist/0UEL66rVxg9p1cN9TqeZCB',
    'St Kitts & Nevis': 'https://open.spotify.com/embed/playlist/6419tHdat2G3HETHAHhVBh',
    'St Lucia': 'https://open.spotify.com/embed/playlist/67KmiVuIO4JLfsqnggMxhq',
    'Saint Vincent & the Grenadines': 'https://open.spotify.com/embed/playlist/2muVQMeRTFngJjtEtz9xwn',
    'Samoa': 'https://open.spotify.com/embed/playlist/43hpfQ67EdFMByKzqma6JG',
    'San Marino': 'https://open.spotify.com/embed/playlist/59i8HLq40eIFSiH39cLvfy',
    'Sao Tome & Principe': 'https://open.spotify.com/embed/playlist/4QFK61htqrf5vCQnRRaYht',
    'Saudi Arabia': 'https://open.spotify.com/embed/playlist/4njur481x33REjpztwh9wO',
    'Senegal': 'https://open.spotify.com/embed/playlist/5MZ87JsRlRwuqYVJpERjiG',
    'Serbia': 'https://open.spotify.com/embed/playlist/0KsWyEIsJpyZtP1PgQVvOD',
    'Seychelles': 'https://open.spotify.com/embed/playlist/3z3rD6dF7UJPNeYmRBDetF',
    'Sierra Leone': 'https://open.spotify.com/embed/playlist/5ljzyALeZMxqC2fHgkUGNY',
    'Singapore': 'https://open.spotify.com/embed/playlist/4DvXytzDbSujWBRmwVH85r',
    'Slovakia': 'https://open.spotify.com/embed/playlist/3RKFpCU8U1W4su54fdk6jF',
    'Slovenia': 'https://open.spotify.com/embed/playlist/3asaVC8KUJtI1DAXsHKv2D',
    'Solomon Islands': 'https://open.spotify.com/embed/playlist/0sMCFiHTzMKgg1QflEKidH',
    'Somalia': 'https://open.spotify.com/embed/playlist/5hOHDErcdm4GjuOl37HMy1',
    'South Africa': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX9wXOYagay8L',
    'South Sudan': 'https://open.spotify.com/embed/playlist/2domD3pH2tbubm1FwhJVw9',
    'Spain': 'https://open.spotify.com/embed/playlist/5hQaM0nbZUOmJfKmn7d1Xr',
    'Sri Lanka': 'https://open.spotify.com/embed/playlist/78jbUTdh5X5qe72rikqrxS',
    'Sudan (the)': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX15iTqq2X8NE',
    'Suriname': 'https://open.spotify.com/embed/playlist/1hXHzQxSj3W7Ejd9H2rU54',
    'Swaziland': 'https://open.spotify.com/embed/playlist/5F1lc49YcCuT6fEQsgv8lw',
    'Sweden': 'https://open.spotify.com/embed/playlist/5sjIhYs9VdRLVRwQimhRq6',
    'Switzerland': 'https://open.spotify.com/embed/playlist/2tPPvU1XMBDO9y6W6muBXG',
    'Syria': 'https://open.spotify.com/embed/playlist/71AaHNo5ZV6AIh7kF65UTY',
    'Korea (the Republic of)': 'https://open.spotify.com/embed/playlist/52Z6bV877kg1F0DvGzmdAw',
    'Taiwan': 'https://open.spotify.com/embed/playlist/37i9dQZF1DX3EPir2rfrqR',
    'Tajikistan': 'https://open.spotify.com/embed/playlist/4mh0GeHzEkgPkVrCxsKQpM',
    'Tanzania': 'https://open.spotify.com/embed/playlist/33JnwuPXfniEPC9uajz92x',
    'Thailand': 'https://open.spotify.com/embed/playlist/3HwPfR9P3OqlId9ADZCrrt',
    'Togo': 'https://open.spotify.com/embed/playlist/1QX521nM9wFdrp8J8p3YyM',
    'Tonga': 'https://open.spotify.com/embed/playlist/4yT338mUv8PeCSX1JgxHZR',
    'Trinidad & Tobago': 'https://open.spotify.com/embed/playlist/7kLbQQaYrdGqMMrFq1h3lX',
    'Tunisia': 'https://open.spotify.com/embed/playlist/0PAK2TYrXeQBrXCMzSELCH',
    'Turkey': 'https://open.spotify.com/embed/playlist/4oKodlbJBRKSssO8LhsisY',
    'Turkmenistan': 'https://open.spotify.com/embed/playlist/4kmst9TqzRUeXBVTj8GQ81',
    'Tuvalu': 'https://open.spotify.com/embed/playlist/2i5vsgc8zPAAdzAYBoRcuR',
    'Uganda': 'https://open.spotify.com/embed/playlist/59TVx2MmmBfg0BqRc7CvqM',
    'Ukraine': 'https://open.spotify.com/embed/playlist/2PaajqPSi1xmO8Pkk8uJQV',
    'United Arab Emirates (the)': 'https://open.spotify.com/embed/playlist/11QSIC8Hx2PMf9nP5LjPge',
    'United Kingdom of Great Britain and Northern Ireland (the)': 'https://open.spotify.com/embed/playlist/37i9dQZF1DWSIaDfaHJHox',
    'United States of America (the)': 'https://open.spotify.com/embed/playlist/5GpLQUSgTkOWHfMVjd61No',
    'Uruguay': 'https://open.spotify.com/embed/playlist/7veYKAgvBaom11iHhdIelV',
    'Uzbekistan': 'https://open.spotify.com/embed/playlist/0G4bPOTAX6R4VvGcW9UZ0U',
    'Vanuatu': 'https://open.spotify.com/embed/playlist/7inTFRfISVdiJzduMwRw5X',
    'Vatican City': 'https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO2nnqSi',
    'Venezuela (Bolivarian Republic of)': 'https://open.spotify.com/embed/playlist/3frQnXFys0NQpGdzsANq1m',
    'Viet Nam': 'https://open.spotify.com/embed/playlist/1mvtazNJybNmsRmeTNjdEf',
    'Yemen': 'https://open.spotify.com/embegud/playlist/37i9dQZF1DX2LJXoyg2yd7',
    'Zambia': 'https://open.spotify.com/embed/playlist/3AxsN9foojNcuPI9OXnVIB',
    'Zimbabwe': 'https://open.spotify.com/embed/playlist/0y9e3OxsNztYAT8m0yXFdO',

    'Greenland': 'https://open.spotify.com/embed/playlist/5K6E8fXPQZqlzGnCwEFluh'
  };

  const getPlaylist = (countryName) => playlists[countryName] || '';
</script>

<div class="bg-antiquewhite rounded-lg  p-3 max-w-sm mx-auto mt-4">
  <h3 class="text-xl font-bold mb-2">Country Info</h3>
  <p class="text-lg">{country || '(no data)'}</p>
  <hr class="my-3" />
  {#if getPlaylist(country)}
  <iframe
    data-testid="embed-iframe"
    title="Spotify playlist"
    style="border-radius:1px"
    src={getPlaylist(country)}
    width="100%"
    height="351"
    frameborder="0"
    allowfullscreen
    allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
    loading="lazy"
  ></iframe>

  {:else if country && country !== 'Loading...' && country !== 'Country not found' && country !== 'Error fetching country'}
  <p class="text-sm mt-3 text-gray-600">No playlist mapped for {country} yet.</p>
  {/if}
</div>

